//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;

#[derive(
    Debug,
    Clone,
    borsh::BorshSerialize,
    borsh::BorshDeserialize,
    PartialEq,
    Eq,
    Hash,
    serde::Serialize,
    serde::Deserialize,
)]
pub enum Venue {
    RaydiumAmm,
    RaydiumClmm {
        pool_price_increases: bool,
    },
    Whirlpools {
        a_to_b: bool,
    },
    MeteoraDlmm,
    MeteoraAmm,
    Phoenix {
        is_buy: bool,
    },
    LifinityV2,
    OpenbookV2 {
        is_bid: bool,
    },
    StabbleStableSwap,
    StabbleWeightedSwap,
    RaydiumCP,
    ObricV2 {
        x_to_y: bool,
    },
    GooseFX,
    ZeroFi {
        expected_amount_out: u64,
    },
    SolFi {
        is_quote_to_base: bool,
    },
    WooFi,
    PumpSwap {
        is_quote_to_base: bool,
    },
    Manifest {
        is_base_in: bool,
    },
    Carrot {
        is_crt_in: bool,
    },
    Rubicon,
    Gavel {
        is_sell: bool,
    },
    SanctumDepositWithdraw {
        is_deposit: bool,
        bridge_stake_seed: Option<u32>,
        split_at: u8,
    },
    Byreal {
        pool_price_increases: bool,
    },
    TesseraV {
        is_bid: bool,
    },
    Aquifer,
    FusionAmm {
        a_to_b: bool,
    },
    ExponentAmm {
        is_buy_pt: bool,
        rem_accounts_until: u8,
    },
    SarosDlmm {
        x_to_y: bool,
    },
    HumidiFi {
        is_quote_to_base: bool,
        swap_id: u64,
    },
    Bonkswap {
        x_to_y: bool,
        price_limit: u128,
    },
    SolFiV2 {
        is_quote_to_base: bool,
    },
    AlphaQ {
        a_to_b: bool,
    },
    PancakeSwap {
        pool_price_increases: bool,
    },
    HashFlow {
        transaction_id: [u8; 32],
        token_from_amount: u64,
        token_to_amount: u64,
        quote_expiry: u64,
        #[serde(with = "serde_big_array::BigArray")]
        signature: [u8; 64],
        recovery_id: u8,
    },
    VaultUnstakepool {
        split_at: [u8; 5],
        lst_amounts: [u64; 5],
        seeds: [u32; 5],
    },
    GoonFi {
        is_bid: bool,
        blacklist_bump: u8,
    },
    RaydiumAmmV2,
    PumpFun {
        is_quote_to_base: bool,
    },
    SarosAmm,
    RaydiumLaunchpad {
        is_quote_to_base: bool,
    },
    MeteoraDammV2,
    Obsidian,
    Hylo {
        input_enum: u8,
        output_enum: u8,
    },
    Vertigo {
        is_buy: bool,
    },
    Adrena {
        is_add_liq: bool,
    },
    Metadao {
        is_buy: bool,
    },
    SanctumInfAddLiquidity {
        lst_value_calc_accs: u8,
        lst_index: u32,
    },
    SanctumInfRemoveLiquidity {
        lst_value_calc_accs: u8,
        lst_index: u32,
    },
    SanctumInfSwap {
        src_lst_value_calc_accs: u8,
        dst_lst_value_calc_accs: u8,
        src_lst_index: u32,
        dst_lst_index: u32,
    },
    MeteoraDBC {
        quote_to_base: bool,
    },
    TitanLimitOrders {
        bumps: [u8; 3],
    },
}
