use carbon_core::{borsh, CarbonDeserialize};

#[derive(
    CarbonDeserialize, Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq, Clone, Hash,
)]
pub enum AdminInstruction {
    AddPool,
    RemovePool,
    AddCustody,
    RemoveCustody,
    Reimburse,
    AddMarket,
    RemoveMarket,
    InitStaking,
    SetAdminSigners,
    SetCustodyConfig,
    SetPermissions,
    SetBorrowRate,
    SetPerpetualsConfig,
    SetPoolConfig,
    SetFlpStakeConfig,
    SetMarketConfig,
    AddCollection,
    WithdrawFees,
    WithdrawSolFees,
    SetCustomOraclePrice,
    SetTestTime,
    UpdateCustody,
    UpdateTokenRatios,
    AddInternalOracle,
    RenameFlp,
    SetFeeShare,
    InitCompounding,
    InitTokenVault,
    SetTokenVaultConfig,
    WithdrawInstantFees,
    DistributeTokenReward,
    SetTokenReward,
    SetTokenStakeLevel,
    InitRevenueTokenAccount,
    ResizeInternalOracle,
    WithdrawUnclaimedTokens,
    InitRebateVault,
    CreateWhitelist,
    SetWhitelistConfig,
}
