use super::super::types::*;

use carbon_core::{borsh, CarbonDeserialize};

#[derive(CarbonDeserialize, Debug)]
#[carbon(discriminator = "0xbeb2e7b831ba670d")]
pub struct WhirlpoolStrategy {
    pub admin_authority: solana_sdk::pubkey::Pubkey,
    pub global_config: solana_sdk::pubkey::Pubkey,
    pub base_vault_authority: solana_sdk::pubkey::Pubkey,
    pub base_vault_authority_bump: u64,
    pub pool: solana_sdk::pubkey::Pubkey,
    pub pool_token_vault_a: solana_sdk::pubkey::Pubkey,
    pub pool_token_vault_b: solana_sdk::pubkey::Pubkey,
    pub tick_array_lower: solana_sdk::pubkey::Pubkey,
    pub tick_array_upper: solana_sdk::pubkey::Pubkey,
    pub position: solana_sdk::pubkey::Pubkey,
    pub position_mint: solana_sdk::pubkey::Pubkey,
    pub position_metadata: solana_sdk::pubkey::Pubkey,
    pub position_token_account: solana_sdk::pubkey::Pubkey,
    pub token_a_vault: solana_sdk::pubkey::Pubkey,
    pub token_b_vault: solana_sdk::pubkey::Pubkey,
    pub deprecated0: [solana_sdk::pubkey::Pubkey; 2],
    pub deprecated1: [u64; 2],
    pub token_a_mint: solana_sdk::pubkey::Pubkey,
    pub token_b_mint: solana_sdk::pubkey::Pubkey,
    pub token_a_mint_decimals: u64,
    pub token_b_mint_decimals: u64,
    pub token_a_amounts: u64,
    pub token_b_amounts: u64,
    pub token_a_collateral_id: u64,
    pub token_b_collateral_id: u64,
    pub scope_prices: solana_sdk::pubkey::Pubkey,
    pub deprecated2: solana_sdk::pubkey::Pubkey,
    pub shares_mint: solana_sdk::pubkey::Pubkey,
    pub shares_mint_decimals: u64,
    pub shares_mint_authority: solana_sdk::pubkey::Pubkey,
    pub shares_mint_authority_bump: u64,
    pub shares_issued: u64,
    pub status: u64,
    pub reward0_amount: u64,
    pub reward0_vault: solana_sdk::pubkey::Pubkey,
    pub reward0_collateral_id: u64,
    pub reward0_decimals: u64,
    pub reward1_amount: u64,
    pub reward1_vault: solana_sdk::pubkey::Pubkey,
    pub reward1_collateral_id: u64,
    pub reward1_decimals: u64,
    pub reward2_amount: u64,
    pub reward2_vault: solana_sdk::pubkey::Pubkey,
    pub reward2_collateral_id: u64,
    pub reward2_decimals: u64,
    pub deposit_cap_usd: u64,
    pub fees_a_cumulative: u64,
    pub fees_b_cumulative: u64,
    pub reward0_amount_cumulative: u64,
    pub reward1_amount_cumulative: u64,
    pub reward2_amount_cumulative: u64,
    pub deposit_cap_usd_per_ixn: u64,
    pub withdrawal_cap_a: WithdrawalCaps,
    pub withdrawal_cap_b: WithdrawalCaps,
    pub max_price_deviation_bps: u64,
    pub swap_vault_max_slippage_bps: u32,
    pub swap_vault_max_slippage_from_reference_bps: u32,
    pub strategy_type: u64,
    pub padding0: u64,
    pub withdraw_fee: u64,
    pub fees_fee: u64,
    pub reward0_fee: u64,
    pub reward1_fee: u64,
    pub reward2_fee: u64,
    pub position_timestamp: u64,
    pub kamino_rewards: [KaminoRewardInfo; 3],
    pub strategy_dex: u64,
    pub raydium_protocol_position_or_base_vault_authority: solana_sdk::pubkey::Pubkey,
    pub allow_deposit_without_invest: u64,
    pub raydium_pool_config_or_base_vault_authority: solana_sdk::pubkey::Pubkey,
    pub deposit_blocked: u8,
    pub creation_status: u8,
    pub invest_blocked: u8,
    pub share_calculation_method: u8,
    pub withdraw_blocked: u8,
    pub reserved_flag2: u8,
    pub local_admin_blocked: u8,
    pub flash_vault_swap_allowed: u8,
    pub reference_swap_price_a: Price,
    pub reference_swap_price_b: Price,
    pub is_community: u8,
    pub rebalance_type: u8,
    pub padding1: [u8; 6],
    pub rebalance_raw: RebalanceRaw,
    pub padding2: [u8; 7],
    pub token_a_fees_from_rewards_cumulative: u64,
    pub token_b_fees_from_rewards_cumulative: u64,
    pub strategy_lookup_table: solana_sdk::pubkey::Pubkey,
    pub last_swap_uneven_step_timestamp: u64,
    pub farm: solana_sdk::pubkey::Pubkey,
    pub rebalances_cap: WithdrawalCaps,
    pub swap_uneven_authority: solana_sdk::pubkey::Pubkey,
    pub token_a_token_program: solana_sdk::pubkey::Pubkey,
    pub token_b_token_program: solana_sdk::pubkey::Pubkey,
    pub pending_admin: solana_sdk::pubkey::Pubkey,
    pub padding3: u64,
    pub padding4: [u128; 13],
    pub padding5: [u128; 32],
    pub padding6: [u128; 32],
    pub padding7: [u128; 32],
}
